# Generated by Django 4.1 on 2022-08-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("email", models.CharField(max_length=255, null=True)),
                ("password", models.CharField(max_length=255, null=True)),
                ("number", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_name", models.CharField(max_length=122, null=True)),
                ("email", models.CharField(max_length=122, null=True)),
                ("address1", models.CharField(max_length=122, null=True)),
                ("address2", models.CharField(max_length=122, null=True)),
                ("city", models.CharField(max_length=122, null=True)),
                ("state", models.CharField(max_length=122, null=True)),
                ("zip", models.CharField(max_length=133, null=True)),
                ("number", models.CharField(max_length=133, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=122, null=True)),
                ("category", models.CharField(max_length=122, null=True)),
                ("subcategory", models.CharField(max_length=122, null=True)),
                ("desc", models.CharField(max_length=122, null=True)),
                ("price", models.IntegerField(null=True)),
                ("publishDate", models.DateField(null=True)),
                ("image", models.ImageField(null=True, upload_to="shop/images")),
            ],
        ),
    ]
